/**
|--------------------------------------------------
| Npm imports
|--------------------------------------------------
*/
import { z } from 'zod';

/**
|--------------------------------------------------
| Current profile schema version
|--------------------------------------------------
*/
const PROFILE_SCHEMA_VERSION = 1;

/**
|--------------------------------------------------
| Supported profile source languages
|--------------------------------------------------
*/
const sourceLanguageSchema = z.enum(['javascript', 'typescript']);

/**
|--------------------------------------------------
| Import formatting rules
|--------------------------------------------------
*/
const importRulesSchema = z.object({
	/**
	|--------------------------------------------------
	| Whether import formatting is enabled
	|--------------------------------------------------
	*/
	enabled: z.boolean(),

	/**
	|--------------------------------------------------
	| Import sorting strategy applied within each
	| configured group
	|--------------------------------------------------
	*/
	sort: z.enum(['full-line-length', 'preserve']),

	/**
	|--------------------------------------------------
	| Ordered import groups recognized by the profile
	|--------------------------------------------------
	*/
	groups: z.array(z.enum(['built-in', 'custom', 'external', 'side-effect'])).min(1),

	/**
	|--------------------------------------------------
	| Whether named imports are reordered using the
	| selected strategy
	|--------------------------------------------------
	*/
	sortNamedImports: z.boolean(),

	/**
	|--------------------------------------------------
	| Module prefixes classified as project-local imports
	|--------------------------------------------------
	*/
	customPrefixes: z.array(z.string().min(1)).optional(),

	/**
	|--------------------------------------------------
	| Optional rendered sections that may combine groups
	|--------------------------------------------------
	*/
	sections: z
		.array(
			z.object({
				/**
			 |--------------------------------------------------
			 | Optional section heading
			 |--------------------------------------------------
			 */
				label: z.string().min(1).optional(),

				/**
			 |--------------------------------------------------
			 | Import groups rendered inside section
			 |--------------------------------------------------
			 */
				groups: z.array(z.enum(['built-in', 'custom', 'external', 'side-effect'])).min(1),
			}),
		)
		.optional(),
});

/**
|--------------------------------------------------
| Semantic comment formatting rules
|--------------------------------------------------
*/
const commentRulesSchema = z.object({
	/**
	|--------------------------------------------------
	| Whether semantic comment generation is enabled
	|--------------------------------------------------
	*/
	enabled: z.boolean(),

	/**
	|--------------------------------------------------
	| Comment syntax generated by Codexa
	|--------------------------------------------------
	*/
	style: z.enum(['block', 'jsdoc', 'line']),

	/**
	|--------------------------------------------------
	| Required amount of semantic detail in generated
	| comments
	|--------------------------------------------------
	*/
	detail: z.enum(['concise', 'detailed']),

	/**
	|--------------------------------------------------
	| Whether every function and method receives a
	| descriptive heading
	|--------------------------------------------------
	*/
	requireFunctionComments: z.boolean(),

	/**
	|--------------------------------------------------
	| Whether DTO and entity properties receive
	| descriptive headings
	|--------------------------------------------------
	*/
	requirePropertyComments: z.boolean(),

	/**
	|--------------------------------------------------
	| Whether meaningful blocks following blank lines
	| require headings
	|--------------------------------------------------
	*/
	requireBlankLineBoundaryComments: z.boolean(),
});

/**
|--------------------------------------------------
| Object formatting rules
|--------------------------------------------------
*/
const objectRulesSchema = z.object({
	/**
	|--------------------------------------------------
	| Object property ordering strategy
	|--------------------------------------------------
	*/
	order: z.enum(['full-line-length', 'preserve']),

	/**
	|--------------------------------------------------
	| Whether Codexa may reorder only objects proven
	| to be order independent
	|--------------------------------------------------
	*/
	safeOnly: z.boolean(),
});

/**
|--------------------------------------------------
| Conditional formatting rules
|--------------------------------------------------
*/
const conditionRulesSchema = z.object({
	/**
	|--------------------------------------------------
	| Whether conditions should favor early guard
	| clauses
	|--------------------------------------------------
	*/
	preferGuardClauses: z.boolean(),

	/**
	|--------------------------------------------------
	| Whether short single-action guards may remain on
	| one line
	|--------------------------------------------------
	*/
	allowSingleLineGuards: z.boolean(),
});

/**
|--------------------------------------------------
| Behavior-preservation validation rules
|--------------------------------------------------
*/
const validationRulesSchema = z.object({
	/**
	|--------------------------------------------------
	| Whether syntax parsing must succeed before a
	| patch can be reviewed
	|--------------------------------------------------
	*/
	requireSyntaxValidation: z.boolean(),

	/**
	|--------------------------------------------------
	| Whether imports and exported symbols must remain
	| behaviorally equivalent
	|--------------------------------------------------
	*/
	requireSymbolPreservation: z.boolean(),
});

/**
|--------------------------------------------------
| Codexa style profile schema
|--------------------------------------------------
*/
const styleProfileSchema = z.object({
	/**
	|--------------------------------------------------
	| Stable profile identifier
	|--------------------------------------------------
	*/
	id: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),

	/**
	|--------------------------------------------------
	| Human-readable profile name
	|--------------------------------------------------
	*/
	name: z.string().min(1),

	/**
	|--------------------------------------------------
	| Semantic version assigned to the profile
	|--------------------------------------------------
	*/
	version: z.string().regex(/^\d+\.\d+\.\d+$/),

	/**
	|--------------------------------------------------
	| Profile schema version understood by Codexa
	|--------------------------------------------------
	*/
	schemaVersion: z.literal(PROFILE_SCHEMA_VERSION),

	/**
	|--------------------------------------------------
	| Description of the profile's intended formatting
	| behavior
	|--------------------------------------------------
	*/
	description: z.string().min(1),

	/**
	|--------------------------------------------------
	| Source languages supported by the profile
	|--------------------------------------------------
	*/
	languages: z.array(sourceLanguageSchema).min(1),

	/**
	|--------------------------------------------------
	| Frameworks explicitly supported by the profile
	|--------------------------------------------------
	*/
	frameworks: z.array(z.string().min(1)),

	/**
	|--------------------------------------------------
	| Formatting and validation rules owned by the
	| profile
	|--------------------------------------------------
	*/
	rules: z.object({
		/**
		|--------------------------------------------------
		| Import formatting configuration
		|--------------------------------------------------
		*/
		imports: importRulesSchema,

		/**
		|--------------------------------------------------
		| Object formatting configuration
		|--------------------------------------------------
		*/
		objects: objectRulesSchema,

		/**
		|--------------------------------------------------
		| Semantic comment configuration
		|--------------------------------------------------
		*/
		comments: commentRulesSchema,

		/**
		|--------------------------------------------------
		| Conditional formatting configuration
		|--------------------------------------------------
		*/
		conditions: conditionRulesSchema,

		/**
		|--------------------------------------------------
		| Behavior-preservation validation configuration
		|--------------------------------------------------
		*/
		validation: validationRulesSchema,
	}),
});

/**
|--------------------------------------------------
| Codexa style profile
|--------------------------------------------------
*/
type StyleProfile = z.infer<typeof styleProfileSchema>;

/**
|--------------------------------------------------
| Parse and validate style profile
|--------------------------------------------------
*/
const parseStyleProfile = (input: unknown) => {
	/**
	|--------------------------------------------------
	| Return validated style profile
	|--------------------------------------------------
	*/
	return styleProfileSchema.parse(input);
};

/**
|--------------------------------------------------
| Safely validate style profile
|--------------------------------------------------
*/
const safeParseStyleProfile = (input: unknown) => {
	/**
	|--------------------------------------------------
	| Return validation result without throwing
	|--------------------------------------------------
	*/
	return styleProfileSchema.safeParse(input);
};

/**
|--------------------------------------------------
| Export profile schema contracts
|--------------------------------------------------
*/
export { parseStyleProfile, styleProfileSchema, safeParseStyleProfile, PROFILE_SCHEMA_VERSION, type StyleProfile };
