/**
|--------------------------------------------------
| Generated style examples
|--------------------------------------------------
*/
// AUTO-GENERATED by scripts/build-style-examples.mjs from docs/examples/*.md.
// Do not edit by hand; edit the source docs and re-run `npm run build:examples`.

/**
|--------------------------------------------------
| Custom imports
|--------------------------------------------------
*/
import type { StyleExample } from './style-pack.js';

/**
|--------------------------------------------------
| Worked input and output example pairs
|--------------------------------------------------
*/
const STYLE_EXAMPLES: StyleExample[] = [
	{
		"category": "function",
		"title": "0 — Convert line comments and order a returned object",
		"input": "const buildUser = (form) => {\n\t// Guard clause\n\tif (!form) return null;\n\n\t// Build payload\n\treturn {\n\t\tpreferences: form.prefs,\n\t\tid: form.id,\n\t\temail: form.email,\n\t\tname: form.name,\n\t};\n};",
		"output": "/**\n|--------------------------------------------------\n| Build user\n|--------------------------------------------------\n*/\nconst buildUser = (form) => {\n\t/**\n\t |--------------------------------------------------\n\t | Guard clause\n\t |--------------------------------------------------\n\t */\n\tif (!form) return null;\n\n\t/**\n\t |--------------------------------------------------\n\t | Prepare payload\n\t |--------------------------------------------------\n\t */\n\treturn {\n\t\tid: form.id,\n\t\tname: form.name,\n\t\temail: form.email,\n\t\tpreferences: form.prefs,\n\t};\n};"
	},
	{
		"category": "function",
		"title": "1 — Guard clause + async",
		"input": "const handleUpdateQuantity = async (q: number) => {\n\tif (q < 1) return;\n\n\tconst res = await update(q);\n};",
		"output": "/**\n|--------------------------------------------------\n| Update quantity\n|--------------------------------------------------\n*/\nconst handleUpdateQuantity = async (q: number) => {\n\t/**\n\t |--------------------------------------------------\n\t | Guard clause\n\t |--------------------------------------------------\n\t */\n\tif (q < 1) return;\n\n\t/**\n\t |--------------------------------------------------\n\t | Make request\n\t |--------------------------------------------------\n\t */\n\tconst res = await update(q);\n};"
	},
	{
		"category": "function",
		"title": "2 — Simple utility",
		"input": "const formatAmount = (n: number) => Number(n).toFixed(2);",
		"output": "/**\n|--------------------------------------------------\n| Format amount\n|--------------------------------------------------\n*/\nconst formatAmount = (n: number) => {\n\t/**\n\t |--------------------------------------------------\n\t | Return result\n\t |--------------------------------------------------\n\t */\n\treturn Number(n).toFixed(2);\n};"
	},
	{
		"category": "function",
		"title": "3 — Early return",
		"input": "const getUser = (user) => {\n\tif (!user) return null;\n\treturn user.name;\n};",
		"output": "/**\n|--------------------------------------------------\n| Get user\n|--------------------------------------------------\n*/\nconst getUser = (user) => {\n\t/**\n\t |--------------------------------------------------\n\t | Guard clause\n\t |--------------------------------------------------\n\t */\n\tif (!user) return null;\n\n\t/**\n\t |--------------------------------------------------\n\t | Return result\n\t |--------------------------------------------------\n\t */\n\treturn user.name;\n};"
	},
	{
		"category": "function",
		"title": "4 — Switch statement",
		"input": "const getStatus = (s) => {\n\tswitch (s) {\n\t\tcase 'ok': return 'OK';\n\t\tdefault: return 'N/A';\n\t}\n};",
		"output": "/**\n|--------------------------------------------------\n| Get status\n|--------------------------------------------------\n*/\nconst getStatus = (s) => {\n\t/**\n\t |--------------------------------------------------\n\t | Determine status\n\t |--------------------------------------------------\n\t */\n\tswitch (s) {\n\t\t/**\n\t\t |--------------------------------------------------\n\t\t | Status is OK\n\t\t |--------------------------------------------------\n\t\t */\n\t\tcase 'ok':\n\t\t\treturn 'OK';\n\n\t\t/**\n\t\t |--------------------------------------------------\n\t\t | Fallback\n\t\t |--------------------------------------------------\n\t\t */\n\t\tdefault:\n\t\t\treturn 'N/A';\n\t}\n};"
	},
	{
		"category": "function",
		"title": "5 — Multiple if/else",
		"input": "const getLabel = (v) => {\n\tif (v > 10) return 'High';\n\telse if (v > 5) return 'Medium';\n\treturn 'Low';\n};",
		"output": "/**\n|--------------------------------------------------\n| Get label\n|--------------------------------------------------\n*/\nconst getLabel = (v) => {\n\t/**\n\t |--------------------------------------------------\n\t | Determine label\n\t |--------------------------------------------------\n\t */\n\tif (v > 10) return 'High';\n\telse if (v > 5) return 'Medium';\n\n\t/**\n\t |--------------------------------------------------\n\t | Returned response\n\t |--------------------------------------------------\n\t */\n\treturn 'Low';\n};"
	},
	{
		"category": "function",
		"title": "6 — React handler",
		"input": "const openModal = () => {\n\tsetOpen(true);\n};",
		"output": "/**\n|--------------------------------------------------\n| Open modal\n|--------------------------------------------------\n*/\nconst openModal = () => {\n\t/**\n\t |--------------------------------------------------\n\t | Update local state\n\t |--------------------------------------------------\n\t */\n\tsetOpen(true);\n};"
	},
	{
		"category": "function",
		"title": "7 — JSX return",
		"input": "const renderEmpty = () => <div>No data</div>;",
		"output": "/**\n|--------------------------------------------------\n| Render empty state\n|--------------------------------------------------\n*/\nconst renderEmpty = () => {\n\t/**\n\t |--------------------------------------------------\n\t | Render content\n\t |--------------------------------------------------\n\t */\n\treturn <div>No data</div>;\n};"
	},
	{
		"category": "function",
		"title": "8 — Nested callbacks",
		"input": "const getNames = (users) => users.map(u => u.name);",
		"output": "/**\n|--------------------------------------------------\n| Get names\n|--------------------------------------------------\n*/\nconst getNames = (users) => {\n\t/**\n\t |--------------------------------------------------\n\t | Process items\n\t |--------------------------------------------------\n\t */\n\treturn users.map((u) => u.name);\n};"
	},
	{
		"category": "function",
		"title": "9 — Inline comment conversion",
		"input": "const fn = () => {\n\t// fetch data\n\tgetData();\n};",
		"output": "/**\n|--------------------------------------------------\n| Fn\n|--------------------------------------------------\n*/\nconst fn = () => {\n\t/**\n\t |--------------------------------------------------\n\t | Fetch data\n\t |--------------------------------------------------\n\t */\n\tgetData();\n};"
	},
	{
		"category": "function",
		"title": "10 — Try/catch",
		"input": "const load = async () => {\n\ttry {\n\t\tawait fetchData();\n\t} catch (e) {\n\t\tconsole.log(e);\n\t}\n};",
		"output": "/**\n|--------------------------------------------------\n| Load data\n|--------------------------------------------------\n*/\nconst load = async () => {\n\ttry {\n\t\t/**\n\t\t |--------------------------------------------------\n\t\t | Fetch data\n\t\t |--------------------------------------------------\n\t\t */\n\t\tawait fetchData();\n\t} catch (e) {\n\t\t/**\n\t\t |--------------------------------------------------\n\t\t | Handle error\n\t\t |--------------------------------------------------\n\t\t */\n\t\tconsole.log(e);\n\t}\n};"
	},
	{
		"category": "function",
		"title": "21 — Prop arrangement",
		"input": "const payload = {\n\tuserId: user.id,\n\tname: user.name,\n\temailAddress: user.email,\n\tid: user._id,\n\tphoneNumber: user.phone,\n\tisActive: user.active,\n};",
		"output": "/**\n|--------------------------------------------------\n| Prepare payload\n|--------------------------------------------------\n*/\nconst payload = {\n\tid: user._id,\n\tuserId: user.id,\n\tname: user.name,\n\tisActive: user.active,\n\tphoneNumber: user.phone,\n\temailAddress: user.email,\n};"
	},
	{
		"category": "function",
		"title": "22 — Prop arrangement - configs",
		"input": "const config = {\n\ttimeout: 5000,\n\tapi: '/v1/users',\n\tretryAttempts: 3,\n\turl: 'https://api.com',\n\tmethod: 'GET',\n\theaders: {},\n};",
		"output": "/**\n|--------------------------------------------------\n| Prepare config\n|--------------------------------------------------\n*/\nconst config = {\n\theaders: {},\n\ttimeout: 5000,\n\tmethod: 'GET',\n\tapi: '/v1/users',\n\tretryAttempts: 3,\n\turl: 'https://api.com',\n};"
	},
	{
		"category": "function",
		"title": "23 — Prop arrangement - with nested objects",
		"input": "const payload = {\n\tuserId: 1,\n\tname: 'Ayo',\n\tmeta: {\n\t\tlongKeyName: true,\n\t\tid: 2,\n\t},\n};",
		"output": "/**\n|--------------------------------------------------\n| Prepare config\n|--------------------------------------------------\n*/\nconst payload = {\n\tuserId: 1,\n\tname: 'Ayo',\n\t/**\n\t|--------------------------------------------------\n\t| Nested meta\n\t|--------------------------------------------------\n\t*/\n\tmeta: {\n\t\tid: 2,\n\t\tlongKeyName: true,\n\t},\n};"
	},
	{
		"category": "function",
		"title": "24 — Prop arrangement - for already arranged props",
		"input": "const data = {\n\tage: 20,\n\tjob: 'dev',\n\tname: 'ayo',\n};",
		"output": "/**\n|--------------------------------------------------\n| Prepare object\n|--------------------------------------------------\n*/\nconst data = {\n\tage: 20,\n\tjob: 'dev',\n\tname: 'ayo',\n};"
	},
	{
		"category": "function",
		"title": "26 — Switch statement with multiline branches",
		"input": "switch (event.type) {\n\tcase 'run.started':\n\t\treturn { ...previous, status: 'running' };\n\tcase 'unit.completed':\n\t\treturn {\n\t\t\t...previous,\n\t\t\tstatus: 'running',\n\t\t\tcompletedUnits: event.completedUnits,\n\t\t\tresults: [...previous.results.filter((r) => r.path !== event.result.path), event.result],\n\t\t};\n\tcase 'run.completed':\n\t\treturn { ...previous, status: 'completed', results: event.results, completedUnits: event.results.length };\n\tcase 'run.cancelled':\n\t\treturn { ...previous, status: 'cancelled' };\n\tcase 'run.failed':\n\t\treturn { ...previous, status: 'failed', error: event.error };\n\tdefault:\n\t\treturn previous;\n}",
		"output": "switch (event.type) {\n\t/**\n\t |--------------------------------------------------\n\t | Run started\n\t |--------------------------------------------------\n\t */\n\tcase 'run.started':\n\t\treturn {\n\t\t\t...previous,\n\t\t\tstatus: 'running',\n\t\t};\n\n\t/**\n\t |--------------------------------------------------\n\t | Individual unit completed\n\t |--------------------------------------------------\n\t */\n\tcase 'unit.completed':\n\t\treturn {\n\t\t\t...previous,\n\t\t\tstatus: 'running',\n\t\t\tcompletedUnits: event.completedUnits,\n\t\t\tresults: [\n\t\t\t\t...previous.results.filter((r) => r.path !== event.result.path),\n\t\t\t\tevent.result,\n\t\t\t],\n\t\t};\n\n\t/**\n\t |--------------------------------------------------\n\t | Run completed\n\t |--------------------------------------------------\n\t */\n\tcase 'run.completed':\n\t\treturn {\n\t\t\t...previous,\n\t\t\tstatus: 'completed',\n\t\t\tresults: event.results,\n\t\t\tcompletedUnits: event.results.length,\n\t\t};\n\n\t/**\n\t |--------------------------------------------------\n\t | Run cancelled\n\t |--------------------------------------------------\n\t */\n\tcase 'run.cancelled':\n\t\treturn {\n\t\t\t...previous,\n\t\t\tstatus: 'cancelled',\n\t\t};\n\n\t/**\n\t |--------------------------------------------------\n\t | Run failed\n\t |--------------------------------------------------\n\t */\n\tcase 'run.failed':\n\t\treturn {\n\t\t\t...previous,\n\t\t\tstatus: 'failed',\n\t\t\terror: event.error,\n\t\t};\n\n\t/**\n\t |--------------------------------------------------\n\t | Fallback\n\t |--------------------------------------------------\n\t */\n\tdefault:\n\t\treturn previous;\n}"
	},
	{
		"category": "hook",
		"title": "0 — Convert line comments and order the returned object",
		"input": "const useToggle = () => {\n\tconst [open, setOpen] = useState(false);\n\tconst [isLoading, setIsLoading] = useState(false);\n\n\t// Handle toggle\n\tconst handleToggle = () => {\n\t\tsetOpen((prev) => !prev);\n\t};\n\n\t// Reset state\n\tconst reset = () => {\n\t\tsetOpen(false);\n\t\tsetIsLoading(false);\n\t};\n\n\treturn {\n\t\tisLoading,\n\t\tsetIsLoading,\n\t\topen,\n\t\tsetOpen,\n\t\treset,\n\t\thandleToggle,\n\t};\n};",
		"output": "/**\n|--------------------------------------------------\n| Use toggle\n|--------------------------------------------------\n*/\nconst useToggle = () => {\n\t/**\n\t |--------------------------------------------------\n\t | Local states\n\t |--------------------------------------------------\n\t */\n\tconst [open, setOpen] = useState(false);\n\tconst [isLoading, setIsLoading] = useState(false);\n\n\t/**\n\t |--------------------------------------------------\n\t | Handle toggle\n\t |--------------------------------------------------\n\t */\n\tconst handleToggle = () => {\n\t\t/**\n\t\t |--------------------------------------------------\n\t\t | Update state\n\t\t |--------------------------------------------------\n\t\t */\n\t\tsetOpen((prev) => !prev);\n\t};\n\n\t/**\n\t |--------------------------------------------------\n\t | Reset state\n\t |--------------------------------------------------\n\t */\n\tconst reset = () => {\n\t\t/**\n\t\t |--------------------------------------------------\n\t\t | Reset local state\n\t\t |--------------------------------------------------\n\t\t */\n\t\tsetOpen(false);\n\t\tsetIsLoading(false);\n\t};\n\n\t/**\n\t |--------------------------------------------------\n\t | Return values\n\t |--------------------------------------------------\n\t */\n\treturn {\n\t\topen,\n\t\treset,\n\t\tsetOpen,\n\t\tisLoading,\n\t\tsetIsLoading,\n\t\thandleToggle,\n\t};\n};"
	},
	{
		"category": "hook",
		"title": "1 — Simple useEffect",
		"input": "useEffect(() => {\n\tgetData();\n}, []);",
		"output": "useEffect(() => {\n\t/**\n\t |--------------------------------------------------\n\t | Fetch data\n\t |--------------------------------------------------\n\t */\n\tgetData();\n}, []);"
	},
	{
		"category": "hook",
		"title": "2 — Guard clause",
		"input": "useEffect(() => {\n\tif (!user) return;\n\tgetProfile();\n}, [user]);",
		"output": "useEffect(() => {\n\t/**\n\t |--------------------------------------------------\n\t | Guard clause\n\t |--------------------------------------------------\n\t */\n\tif (!user) return;\n\n\t/**\n\t |--------------------------------------------------\n\t | Fetch profile\n\t |--------------------------------------------------\n\t */\n\tgetProfile();\n}, [user]);"
	},
	{
		"category": "hook",
		"title": "3 — Derived values + logic",
		"input": "useEffect(() => {\n\tconst isEmpty = !items || items.length === 0;\n\n\tif (isEmpty) {\n\t\tsetEmpty(true);\n\t}\n}, [items]);",
		"output": "useEffect(() => {\n\t/**\n\t |--------------------------------------------------\n\t | Determine empty state\n\t |--------------------------------------------------\n\t */\n\tconst isEmpty = !items || items.length === 0;\n\n\t/**\n\t |--------------------------------------------------\n\t | Handle empty state\n\t |--------------------------------------------------\n\t */\n\tif (isEmpty) {\n\t\tsetEmpty(true);\n\t}\n}, [items]);"
	},
	{
		"category": "hook",
		"title": "4 — Reset logic",
		"input": "useEffect(() => {\n\tif (!value) {\n\t\tsetData(null);\n\t\tsetLoading(false);\n\t}\n}, [value]);",
		"output": "useEffect(() => {\n\t/**\n\t |--------------------------------------------------\n\t | Reset state when value is empty\n\t |--------------------------------------------------\n\t */\n\tif (!value) {\n\t\tsetData(null);\n\t\tsetLoading(false);\n\t}\n}, [value]);"
	},
	{
		"category": "hook",
		"title": "5 — Multiple logical sections",
		"input": "useEffect(() => {\n\tconst ready = data && data.length;\n\n\tif (!ready) return;\n\n\tprocess(data);\n\tsetReady(true);\n}, [data]);",
		"output": "useEffect(() => {\n\t/**\n\t |--------------------------------------------------\n\t | Determine readiness\n\t |--------------------------------------------------\n\t */\n\tconst ready = data && data.length;\n\n\t/**\n\t |--------------------------------------------------\n\t | Guard clause\n\t |--------------------------------------------------\n\t */\n\tif (!ready) return;\n\n\t/**\n\t |--------------------------------------------------\n\t | Process data\n\t |--------------------------------------------------\n\t */\n\tprocess(data);\n\n\t/**\n\t |--------------------------------------------------\n\t | Update state\n\t |--------------------------------------------------\n\t */\n\tsetReady(true);\n}, [data]);"
	},
	{
		"category": "hook",
		"title": "6 — Cleanup function",
		"input": "useEffect(() => {\n\tconst timer = setTimeout(() => {\n\t\tsetDone(true);\n\t}, 300);\n\n\treturn () => clearTimeout(timer);\n}, []);",
		"output": "useEffect(() => {\n\t/**\n\t |--------------------------------------------------\n\t | Start timer\n\t |--------------------------------------------------\n\t */\n\tconst timer = setTimeout(() => {\n\t\tsetDone(true);\n\t}, 300);\n\n\t/**\n\t |--------------------------------------------------\n\t | Return cleanup\n\t |--------------------------------------------------\n\t */\n\treturn () => clearTimeout(timer);\n}, []);"
	},
	{
		"category": "hook",
		"title": "8 — useMemo",
		"input": "const total = useMemo(() => {\n\treturn items.reduce((a, b) => a + b.price, 0);\n}, [items]);",
		"output": "const total = useMemo(() => {\n\t/**\n\t |--------------------------------------------------\n\t | Return memoized value\n\t |--------------------------------------------------\n\t */\n\treturn items.reduce((a, b) => a + b.price, 0);\n}, [items]);"
	},
	{
		"category": "hook",
		"title": "10 — useCallback",
		"input": "const handleClose = useCallback(() => {\n\tsetOpen(false);\n\tsetSelected(null);\n}, []);",
		"output": "const handleClose = useCallback(() => {\n\t/**\n\t |--------------------------------------------------\n\t | Reset local state\n\t |--------------------------------------------------\n\t */\n\tsetOpen(false);\n\tsetSelected(null);\n}, []);"
	},
	{
		"category": "hook",
		"title": "12 — Custom hook",
		"input": "const useData = () => {\n\tconst [data, setData] = useState(null);\n\n\tuseEffect(() => {\n\t\tgetData().then(setData);\n\t}, []);\n\n\treturn { data };\n};",
		"output": "const useData = () => {\n\t/**\n\t |--------------------------------------------------\n\t | Local states\n\t |--------------------------------------------------\n\t */\n\tconst [data, setData] = useState(null);\n\n\t/**\n\t |--------------------------------------------------\n\t | Effects\n\t |--------------------------------------------------\n\t */\n\tuseEffect(() => {\n\t\t/**\n\t\t |--------------------------------------------------\n\t\t | Fetch data\n\t\t |--------------------------------------------------\n\t\t */\n\t\tgetData().then(setData);\n\t}, []);\n\n\t/**\n\t |--------------------------------------------------\n\t | Return values\n\t |--------------------------------------------------\n\t */\n\treturn { data };\n};"
	},
	{
		"category": "hook",
		"title": "15 — Reorder useState declarations by length",
		"input": "const [locationResults, setLocationResults] = React.useState<LocationResult | null>(null);\nconst [value, setValue] = React.useState<any>([]);",
		"output": "const [value, setValue] = React.useState<any>([]);\nconst [locationResults, setLocationResults] = React.useState<LocationResult | null>(null);"
	},
	{
		"category": "hook",
		"title": "16 — Reorder mixed-length useState group",
		"input": "const [selectedOrganisation, setSelectedOrganisation] = useState<Organisation | null>(null);\nconst [open, setOpen] = useState(false);\nconst [loading, setLoading] = useState(false);\nconst [searchQuery, setSearchQuery] = useState('');",
		"output": "const [open, setOpen] = useState(false);\nconst [loading, setLoading] = useState(false);\nconst [searchQuery, setSearchQuery] = useState('');\nconst [selectedOrganisation, setSelectedOrganisation] = useState<Organisation | null>(null);"
	},
	{
		"category": "hook",
		"title": "17 — Multi-line declaration sorts by combined length",
		"input": "const [selectedOrganisation, setSelectedOrganisation] = useState<\n\tOrganisation | null\n>(null);\nconst [open, setOpen] = useState(false);",
		"output": "const [open, setOpen] = useState(false);\nconst [selectedOrganisation, setSelectedOrganisation] = useState<\n\tOrganisation | null\n>(null);"
	},
	{
		"category": "hook",
		"title": "18 — Separate groups (blank line between) sorted independently",
		"input": "const [locationResults, setLocationResults] = useState<Result[]>([]);\nconst [value, setValue] = useState('');\n\nconst [selectedItem, setSelectedItem] = useState<Item | null>(null);\nconst [open, setOpen] = useState(false);",
		"output": "const [value, setValue] = useState('');\nconst [open, setOpen] = useState(false);\nconst [selectedItem, setSelectedItem] = useState<Item | null>(null);\nconst [locationResults, setLocationResults] = useState<Result[]>([]);"
	},
	{
		"category": "hook",
		"title": "19 — Reorder useRef declarations by length",
		"input": "const scrollPositionRef = useRef(0);\nconst animationRef = useRef<number>();\nconst dragStartRef = useRef({ x: 0, scrollLeft: 0 });\nconst scrollContainerRef = useRef<HTMLDivElement>(null);\nconst isPausedRef = useRef(false);",
		"output": "/**\n |--------------------------------------------------\n | Refs\n |--------------------------------------------------\n */\nconst animationRef = useRef<number>();\nconst isPausedRef = useRef<boolean>(false);\nconst scrollPositionRef = useRef<number>(0);\nconst scrollContainerRef = useRef<HTMLDivElement>(null);\nconst dragStartRef = useRef<{x:number; scrollLeft:number}>({ x: 0, scrollLeft: 0 });"
	},
	{
		"category": "hook",
		"title": "21 — Nested function inside hook must be formatted",
		"input": "useEffect(() => {\n\tconst handle = () => {\n\t\tsetValue(1);\n\t};\n}, []);",
		"output": "useEffect(() => {\n\t/**\n\t |--------------------------------------------------\n\t | Handle update\n\t |--------------------------------------------------\n\t */\n\tconst handle = () => {\n\t\t/**\n\t\t |--------------------------------------------------\n\t\t | Update state\n\t\t |--------------------------------------------------\n\t\t */\n\t\tsetValue(1);\n\t};\n}, []);"
	},
	{
		"category": "import",
		"title": "1 — Basic grouping",
		"input": "import STBText from '@/src/components/STBText';\nimport React from 'react';\nimport { View } from 'react-native';\nimport ScreenWrapper from '@/src/components/ScreenWrapper';",
		"output": "/**\n|--------------------------------------------------\n| Npm imports\n|--------------------------------------------------\n*/\nimport React from 'react';\nimport { View } from 'react-native';\n\n/**\n|--------------------------------------------------\n| Custom imports\n|--------------------------------------------------\n*/\nimport STBText from '@/src/components/STBText';\nimport ScreenWrapper from '@/src/components/ScreenWrapper';"
	},
	{
		"category": "import",
		"title": "2 — With multiple npm libraries",
		"input": "import clsx from 'clsx';\nimport React from 'react';\nimport { View } from 'react-native';\nimport axios from 'axios';\nimport Button from '@/components/ui/button';",
		"output": "/**\n|--------------------------------------------------\n| Npm imports\n|--------------------------------------------------\n*/\nimport clsx from 'clsx';\nimport React from 'react';\nimport axios from 'axios';\nimport { View } from 'react-native';\n\n/**\n|--------------------------------------------------\n| Custom imports\n|--------------------------------------------------\n*/\nimport Button from '@/components/ui/button';"
	},
	{
		"category": "import",
		"title": "3 — Long destructured imports",
		"input": "import { View, Text, Pressable, ScrollView } from 'react-native';\nimport React from 'react';",
		"output": "/**\n|--------------------------------------------------\n| Npm imports\n|--------------------------------------------------\n*/\nimport {\n    View,\n\tText,\n\tPressable,\n\tScrollView,\n} from 'react-native';\nimport React from 'react';"
	},
	{
		"category": "import",
		"title": "4 — Already grouped but unordered",
		"input": "/**\n|--------------------------------------------------\n| Npm imports\n|--------------------------------------------------\n*/\nimport { View } from 'react-native';\nimport React from 'react';\nimport clsx from 'clsx';",
		"output": "/**\n|--------------------------------------------------\n| Npm imports\n|--------------------------------------------------\n*/\nimport clsx from 'clsx';\nimport React from 'react';\nimport { View } from 'react-native';"
	},
	{
		"category": "import",
		"title": "5 — Mixed imports (common real-world case)",
		"input": "import { useState } from 'react';\nimport STBText from '@/src/components/STBText';\nimport axios from 'axios';\nimport ScreenWrapper from '@/src/components/ScreenWrapper';\nimport React from 'react';",
		"output": "/**\n|--------------------------------------------------\n| Npm imports\n|--------------------------------------------------\n*/\nimport React from 'react';\nimport axios from 'axios';\nimport { useState } from 'react';\n\n/**\n|--------------------------------------------------\n| Custom imports\n|--------------------------------------------------\n*/\nimport STBText from '@/src/components/STBText';\nimport ScreenWrapper from '@/src/components/ScreenWrapper';"
	},
	{
		"category": "import",
		"title": "6 — With hooks and UI libs",
		"input": "import { useQuery } from '@tanstack/react-query';\nimport React from 'react';\nimport { Pressable, View } from 'react-native';\nimport Button from '@/components/ui/button';\nimport TitleHeader from '@/components/TitleHeader';",
		"output": "/**\n|--------------------------------------------------\n| Npm imports\n|--------------------------------------------------\n*/\nimport React from 'react';\nimport { Pressable, View } from 'react-native';\nimport { useQuery } from '@tanstack/react-query';\n\n/**\n|--------------------------------------------------\n| Custom imports\n|--------------------------------------------------\n*/\nimport Button from '@/components/ui/button';\nimport TitleHeader from '@/components/TitleHeader';"
	},
	{
		"category": "import",
		"title": "7 — Edge case (only custom imports)",
		"input": "import STBText from '@/src/components/STBText';\nimport ScreenWrapper from '@/src/components/ScreenWrapper';",
		"output": "/**\n|--------------------------------------------------\n| Custom imports\n|--------------------------------------------------\n*/\nimport STBText from '@/src/components/STBText';\nimport ScreenWrapper from '@/src/components/ScreenWrapper';"
	},
	{
		"category": "import",
		"title": "8 — Edge case (only npm imports)",
		"input": "import React from 'react';\nimport axios from 'axios';\nimport clsx from 'clsx';",
		"output": "/**\n|--------------------------------------------------\n| Npm imports\n|--------------------------------------------------\n*/\nimport clsx from 'clsx';\nimport React from 'react';\nimport axios from 'axios';"
	},
	{
		"category": "view",
		"title": "1 — Grouped image section",
		"input": "return (\n\t<div>\n\t\t<ProductImage src={image} />\n\t\t{showBadge && <span>New</span>}\n\t\t<button onClick={handleWishlist}>Wish</button>\n\t</div>\n);",
		"output": "return (\n\t<div>\n\t\t{/**\n\t\t|--------------------------------------------------\n\t\t| Image wrapper\n\t\t|--------------------------------------------------\n\t\t*/}\n\t\t<div>\n\t\t\t{/**\n\t\t\t|--------------------------------------------------\n\t\t\t| Product image\n\t\t\t|--------------------------------------------------\n\t\t\t*/}\n\t\t\t<ProductImage src={image} />\n\n\t\t\t{/**\n\t\t\t|--------------------------------------------------\n\t\t\t| Product badge\n\t\t\t|--------------------------------------------------\n\t\t\t*/}\n\t\t\t{showBadge && <span>New</span>}\n\n\t\t\t{/**\n\t\t\t|--------------------------------------------------\n\t\t\t| Wish list button\n\t\t\t|--------------------------------------------------\n\t\t\t*/}\n\t\t\t<button onClick={handleWishlist}>Wish</button>\n\t\t</div>\n\t</div>\n);"
	},
	{
		"category": "view",
		"title": "2 — Grouping related product information",
		"input": "return (\n\t<div>\n\t\t<h1>{product.name}</h1>\n\t\t<span>{product.volume}</span>\n\t\t<span>{product.price}</span>\n\t</div>\n);",
		"output": "return (\n\t<div>\n\t\t{/**\n\t\t|--------------------------------------------------\n\t\t| Product information\n\t\t|--------------------------------------------------\n\t\t*/}\n\t\t<div>\n\t\t\t{/**\n\t\t\t|--------------------------------------------------\n\t\t\t| Product name and volume\n\t\t\t|--------------------------------------------------\n\t\t\t*/}\n\t\t\t<div>\n\t\t\t\t<h1>{product.name}</h1>\n\t\t\t\t<span>{product.volume}</span>\n\t\t\t</div>\n\n\t\t\t{/**\n\t\t\t|--------------------------------------------------\n\t\t\t| Product price\n\t\t\t|--------------------------------------------------\n\t\t\t*/}\n\t\t\t<span>{product.price}</span>\n\t\t</div>\n\t</div>\n);"
	},
	{
		"category": "view",
		"title": "3 — Mobile and desktop representations grouped separately",
		"input": "return (\n\t<div>\n\t\t<div className=\"md:hidden\">{mobilePrice}</div>\n\t\t<div className=\"hidden md:block\">{desktopPrice}</div>\n\t</div>\n);",
		"output": "return (\n\t<div>\n\t\t{/**\n\t\t|--------------------------------------------------\n\t\t| Pricing section\n\t\t|--------------------------------------------------\n\t\t*/}\n\t\t<div>\n\t\t\t{/**\n\t\t\t|--------------------------------------------------\n\t\t\t| Mobile view\n\t\t\t|--------------------------------------------------\n\t\t\t*/}\n\t\t\t<div className=\"md:hidden\">{mobilePrice}</div>\n\n\t\t\t{/**\n\t\t\t|--------------------------------------------------\n\t\t\t| Desktop view\n\t\t\t|--------------------------------------------------\n\t\t\t*/}\n\t\t\t<div className=\"hidden md:block\">{desktopPrice}</div>\n\t\t</div>\n\t</div>\n);"
	},
	{
		"category": "view",
		"title": "4 — B2B and B2C grouped separately",
		"input": "return (\n\t<div>\n\t\t{siteMode === 'B2B' ? <span>{cartonPrice}</span> : <span>{unitPrice}</span>}\n\t</div>\n);",
		"output": "return (\n\t<div>\n\t\t{/**\n\t\t|--------------------------------------------------\n\t\t| Price representation\n\t\t|--------------------------------------------------\n\t\t*/}\n\t\t<div>\n\t\t\t{siteMode === 'B2B' ? (\n\t\t\t\t/**\n\t\t\t\t|--------------------------------------------------\n\t\t\t\t| B2B View\n\t\t\t\t|--------------------------------------------------\n\t\t\t\t*/\n\t\t\t\t<span>{cartonPrice}</span>\n\t\t\t) : (\n\t\t\t\t/**\n\t\t\t\t|--------------------------------------------------\n\t\t\t\t| B2C View\n\t\t\t\t|--------------------------------------------------\n\t\t\t\t*/\n\t\t\t\t<span>{unitPrice}</span>\n\t\t\t)}\n\t\t</div>\n\t</div>\n);"
	},
	{
		"category": "view",
		"title": "5 — Action area grouped",
		"input": "return (\n\t<div>\n\t\t<QuantityChanger qty={qty} />\n\t\t<Button onClick={handleAddToCart}>Add to cart</Button>\n\t</div>\n);",
		"output": "return (\n\t<div>\n\t\t{/**\n\t\t|--------------------------------------------------\n\t\t| Action buttons\n\t\t|--------------------------------------------------\n\t\t*/}\n\t\t<div>\n\t\t\t{/**\n\t\t\t|--------------------------------------------------\n\t\t\t| Quantity changer\n\t\t\t|--------------------------------------------------\n\t\t\t*/}\n\t\t\t<QuantityChanger qty={qty} />\n\n\t\t\t{/**\n\t\t\t|--------------------------------------------------\n\t\t\t| Add to cart button\n\t\t\t|--------------------------------------------------\n\t\t\t*/}\n\t\t\t<Button onClick={handleAddToCart}>Add to cart</Button>\n\t\t</div>\n\t</div>\n);"
	},
	{
		"category": "view",
		"title": "6 — Loading, empty, and content states grouped",
		"input": "return (\n\t<div>\n\t\t{isLoading ? <Loader /> : items.length ? <List items={items} /> : <EmptyState />}\n\t</div>\n);",
		"output": "return (\n\t<div>\n\t\t{/**\n\t\t|--------------------------------------------------\n\t\t| Content state\n\t\t|--------------------------------------------------\n\t\t*/}\n\t\t<div>\n\t\t\t{isLoading ? (\n\t\t\t\t/**\n\t\t\t\t|--------------------------------------------------\n\t\t\t\t| Loading state\n\t\t\t\t|--------------------------------------------------\n\t\t\t\t*/\n\t\t\t\t<Loader />\n\t\t\t) : items.length ? (\n\t\t\t\t/**\n\t\t\t\t|--------------------------------------------------\n\t\t\t\t| Populated state\n\t\t\t\t|--------------------------------------------------\n\t\t\t\t*/\n\t\t\t\t<List items={items} />\n\t\t\t) : (\n\t\t\t\t/**\n\t\t\t\t|--------------------------------------------------\n\t\t\t\t| Empty state\n\t\t\t\t|--------------------------------------------------\n\t\t\t\t*/\n\t\t\t\t<EmptyState />\n\t\t\t)}\n\t\t</div>\n\t</div>\n);"
	},
	{
		"category": "view",
		"title": "7 — Full product card grouping pattern",
		"input": "return (\n\t<div>\n\t\t<div>\n\t\t\t<ProductImage />\n\t\t\t<button>Wish</button>\n\t\t</div>\n\t\t<div>\n\t\t\t<h1>{name}</h1>\n\t\t\t<span>{volume}</span>\n\t\t\t<span>{price}</span>\n\t\t</div>\n\t\t<div>\n\t\t\t<QuantityChanger qty={qty} />\n\t\t\t<Button>Add</Button>\n\t\t</div>\n\t</div>\n);",
		"output": "return (\n\t<div>\n\t\t{/**\n\t\t|--------------------------------------------------\n\t\t| Image wrapper\n\t\t|--------------------------------------------------\n\t\t*/}\n\t\t<div>\n\t\t\t{/**\n\t\t\t|--------------------------------------------------\n\t\t\t| Product image\n\t\t\t|--------------------------------------------------\n\t\t\t*/}\n\t\t\t<ProductImage />\n\n\t\t\t{/**\n\t\t\t|--------------------------------------------------\n\t\t\t| Wish list button\n\t\t\t|--------------------------------------------------\n\t\t\t*/}\n\t\t\t<button>Wish</button>\n\t\t</div>\n\n\t\t{/**\n\t\t|--------------------------------------------------\n\t\t| Product information\n\t\t|--------------------------------------------------\n\t\t*/}\n\t\t<div>\n\t\t\t{/**\n\t\t\t|--------------------------------------------------\n\t\t\t| Product name and volume\n\t\t\t|--------------------------------------------------\n\t\t\t*/}\n\t\t\t<div>\n\t\t\t\t<h1>{name}</h1>\n\t\t\t\t<span>{volume}</span>\n\t\t\t</div>\n\n\t\t\t{/**\n\t\t\t|--------------------------------------------------\n\t\t\t| Product price\n\t\t\t|--------------------------------------------------\n\t\t\t*/}\n\t\t\t<span>{price}</span>\n\t\t</div>\n\n\t\t{/**\n\t\t|--------------------------------------------------\n\t\t| Action buttons\n\t\t|--------------------------------------------------\n\t\t*/}\n\t\t<div>\n\t\t\t{/**\n\t\t\t|--------------------------------------------------\n\t\t\t| Quantity changer\n\t\t\t|--------------------------------------------------\n\t\t\t*/}\n\t\t\t<QuantityChanger qty={qty} />\n\n\t\t\t{/**\n\t\t\t|--------------------------------------------------\n\t\t\t| Add to cart button\n\t\t\t|--------------------------------------------------\n\t\t\t*/}\n\t\t\t<Button>Add</Button>\n\t\t</div>\n\t</div>\n);"
	},
	{
		"category": "view",
		"title": "8 — Grouped header UI",
		"input": "return (\n\t<View>\n\t\t<TitleHeader title=\"Shop\" />\n\t\t<TextInput value={search} onChangeText={setSearch} />\n\t\t<Tabs tabs={tabs} />\n\t</View>\n);",
		"output": "return (\n\t<View>\n\t\t{/**\n\t\t|--------------------------------------------------\n\t\t| Header section\n\t\t|--------------------------------------------------\n\t\t*/}\n\t\t<View>\n\t\t\t{/**\n\t\t\t|--------------------------------------------------\n\t\t\t| Title header\n\t\t\t|--------------------------------------------------\n\t\t\t*/}\n\t\t\t<TitleHeader title=\"Shop\" />\n\n\t\t\t{/**\n\t\t\t|--------------------------------------------------\n\t\t\t| Search input\n\t\t\t|--------------------------------------------------\n\t\t\t*/}\n\t\t\t<TextInput value={search} onChangeText={setSearch} />\n\n\t\t\t{/**\n\t\t\t|--------------------------------------------------\n\t\t\t| Tabs\n\t\t\t|--------------------------------------------------\n\t\t\t*/}\n\t\t\t<Tabs tabs={tabs} />\n\t\t</View>\n\t</View>\n);"
	},
	{
		"category": "view",
		"title": "9 — Grouped list section",
		"input": "return (\n\t<View>\n\t\t{items.map((item) => (\n\t\t\t<Card key={item.id}>{item.name}</Card>\n\t\t))}\n\t</View>\n);",
		"output": "return (\n\t<View>\n\t\t{/**\n\t\t|--------------------------------------------------\n\t\t| Product list\n\t\t|--------------------------------------------------\n\t\t*/}\n\t\t<View>\n\t\t\t{items.map((item) => (\n\t\t\t\t<Card key={item.id}>{item.name}</Card>\n\t\t\t))}\n\t\t</View>\n\t</View>\n);"
	},
	{
		"category": "view",
		"title": "10 — Existing UI comment normalization",
		"input": "return (\n\t<div>\n\t\t{/* image area */}\n\t\t<div>\n\t\t\t<ProductImage />\n\t\t</div>\n\t</div>\n);",
		"output": "return (\n\t<div>\n\t\t{/**\n\t\t|--------------------------------------------------\n\t\t| Image wrapper\n\t\t|--------------------------------------------------\n\t\t*/}\n\t\t<div>\n\t\t\t<ProductImage />\n\t\t</div>\n\t</div>\n);"
	},
	{
		"category": "view",
		"title": "11 — Top-level file formatting with rendered view grouping",
		"input": "import React from 'react';\nimport { View } from 'react-native';\nimport STBText from '@/src/components/STBText';\n\nconst EmptyState = () => {\n\treturn <View><STBText>No data found</STBText></View>;\n};\n\nexport default EmptyState;",
		"output": "/**\n|--------------------------------------------------\n| Npm imports\n|--------------------------------------------------\n*/\nimport React from 'react';\nimport { View } from 'react-native';\n\n/**\n|--------------------------------------------------\n| Custom imports\n|--------------------------------------------------\n*/\nimport STBText from '@/src/components/STBText';\n\n/**\n|--------------------------------------------------\n| Empty state\n|--------------------------------------------------\n*/\nconst EmptyState = () => {\n\t/**\n\t |--------------------------------------------------\n\t | Rendered view\n\t |--------------------------------------------------\n\t */\n\treturn (\n\t\t<View>\n\t\t\t{/**\n\t\t\t|--------------------------------------------------\n\t\t\t| Content\n\t\t\t|--------------------------------------------------\n\t\t\t*/}\n\t\t\t<STBText>No data found</STBText>\n\t\t</View>\n\t);\n};\n\nexport default EmptyState;"
	},
	{
		"category": "view",
		"title": "12 — Inline callback with grouped logic preserved",
		"input": "<button\n\tonClick={() => {\n\t\tif (!isAuthenticated) {\n\t\t\ttoast({ title: 'Login required' });\n\t\t\treturn;\n\t\t}\n\t\thandleAddToCart();\n\t}}\n>\n\tAdd\n</button>",
		"output": "<button\n\tonClick={() => {\n\t\t/**\n\t\t |--------------------------------------------------\n\t\t | Guard clause\n\t\t |--------------------------------------------------\n\t\t */\n\t\tif (!isAuthenticated) {\n\t\t\ttoast({ title: 'Login required' });\n\t\t\treturn;\n\t\t}\n\n\t\t/**\n\t\t |--------------------------------------------------\n\t\t | Handle add to cart\n\t\t |--------------------------------------------------\n\t\t */\n\t\thandleAddToCart();\n\t}}\n>\n\tAdd\n</button>"
	},
	{
		"category": "view",
		"title": "13 — JSX attributes sorted by full string length",
		"input": "<div\n\tref={scrollContainerRef}\n\tclassName=\"flex whitespace-nowrap will-change-transform cursor-grab active:cursor-grabbing select-none\"\n\tonMouseEnter={pauseOnHover ? handleMouseEnter : undefined}\n\tonMouseLeave={pauseOnHover ? handleMouseLeave : undefined}\n\tonMouseDown={handleMouseDown}\n\tonMouseMove={handleMouseMove}\n\tonMouseUp={handleMouseUp}\n\tonTouchStart={handleTouchStart}\n\tonTouchMove={handleTouchMove}\n\tonTouchEnd={handleTouchEnd}\n\tstyle={{ touchAction: 'pan-y' }}\n>",
		"output": "<div\n\tref={scrollContainerRef}\n\tonMouseUp={handleMouseUp}\n\tonTouchEnd={handleTouchEnd}\n\tonMouseDown={handleMouseDown}\n\tonMouseMove={handleMouseMove}\n\tonTouchMove={handleTouchMove}\n\tonTouchStart={handleTouchStart}\n\tstyle={{ touchAction: 'pan-y' }}\n\tonMouseEnter={pauseOnHover ? handleMouseEnter : undefined}\n\tonMouseLeave={pauseOnHover ? handleMouseLeave : undefined}\n\tclassName=\"flex whitespace-nowrap will-change-transform cursor-grab active:cursor-grabbing select-none\"\n>"
	},
	{
		"category": "view",
		"title": "14 — Component props destructuring sorted by name length",
		"input": "const Component = ({\n\tchildren,\n\tautoplayDelay,\n\tshowControls,\n\tautoplay,\n}: Props) => {};",
		"output": "const Component = ({\n\tchildren,\n\tautoplay,\n\tshowControls,\n\tautoplayDelay,\n}: Props) => {};"
	}
];

/**
|--------------------------------------------------
| Export generated style examples
|--------------------------------------------------
*/
export { STYLE_EXAMPLES };
